name: Sync Blog

on:
  push:
    branches:
      - main # 也可以设置为 main 分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
      - uses: actions/checkout@main
      - name: 安装node.js
        uses: actions/setup-node@main
        with:
          node-version: lts/*

      # 安装依赖
      - name: 安装依赖
        run: npm install
      # 打包
      - name: 打包
        run: npm run build
      # 上传到服务器
      - name: 发布到服务器
        uses: easingthemes/ssh-deploy@main
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # SCP参数
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: "dist"
          # 服务器ip
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/home/coj/coj-frontend"
